/**
 * Ed25519 provenance for the auto-refreshed critical helpers (ADR-174 security).
 *
 * The helper auto-refresh copies auto-EXECUTING hook code (`hook-handler.cjs`
 * etc.) from the installed package into a project. npm verifies the tarball at
 * INSTALL time, but not the files on disk afterward — a sibling package's
 * postinstall (or disk tampering) could overwrite them, and the refresh would
 * faithfully propagate the tampered code. This gate closes that: every helper
 * is verified against a swarmlo-signed manifest before install, and a mismatch is
 * REFUSED (fail-closed). The public key is baked in below; the private key is
 * never in the repo (see scripts/sign-helpers.mjs).
 *
 * Native Node crypto (RFC 8032 Ed25519), zero external deps — same primitive as
 * src/appliance/rvfa-signing.ts.
 */
import { createHash, verify as edVerify } from 'crypto';

/**
 * Swarmlo helper-signing PUBLIC key (safe to commit). The matching private key is
 * held out-of-repo and provided to scripts/sign-helpers.mjs at publish time via
 * $SWARMLO_HELPERS_SIGNING_KEY. Rotating the key = replace this constant + re-sign.
 *
 * ROTATED 2026-08-18 (fork rebrand): the upstream ruvnet key cannot sign fork
 * content. New keypair generated by the fork owner; private key held at
 * ~/.swarmlo/helpers-signing.key (out-of-repo). Pre-rebrand manifests signed
 * with the upstream key no longer verify after this rotation.
 */
export const SWARMLO_HELPERS_PUBKEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA7bjJiEJpq5sDBLH4yGNqudPWqNOhW+1+2hJ6mmo8iuQ=
-----END PUBLIC KEY-----`;

export const HELPERS_MANIFEST_FILE = 'helpers.manifest.json';

export interface HelpersManifest {
  version: string;
  files: Record<string, string>; // helper name -> sha256 hex
}
export interface SignedHelpersManifest {
  manifest: HelpersManifest;
  signature: string; // base64 Ed25519 signature over canonicalManifestBytes(manifest)
  algorithm: 'ed25519';
}

export function sha256Hex(content: string | Buffer): string {
  // Canonicalize line endings (CRLF → LF) before hashing so signatures signed on
  // Windows match checkouts on Linux/CI, where git's autocrlf stores LF on disk.
  const normalized =
    typeof content === 'string' ? content.replace(/\r\n/g, '\n') : content.toString('utf8').replace(/\r\n/g, '\n');
  return createHash('sha256').update(normalized, 'utf8').digest('hex');
}

/**
 * Deterministic canonical bytes of a manifest — file keys sorted so the signer
 * and verifier agree byte-for-byte regardless of object insertion order.
 */
export function canonicalManifestBytes(m: HelpersManifest): Buffer {
  const files: Record<string, string> = {};
  for (const k of Object.keys(m.files).sort()) files[k] = m.files[k];
  return Buffer.from(JSON.stringify({ version: m.version, files }), 'utf-8');
}

/**
 * Verify a signed helpers manifest against swarmlo's public key. Returns the
 * trusted file->sha256 manifest, or null on ANY failure (bad signature,
 * malformed JSON, wrong algorithm). Fail-closed — the caller MUST refuse to
 * install unverified helpers.
 */
export function verifyHelpersManifest(
  signedJson: string,
  pubkeyPem: string = SWARMLO_HELPERS_PUBKEY,
): HelpersManifest | null {
  try {
    const signed = JSON.parse(signedJson) as SignedHelpersManifest;
    if (!signed || signed.algorithm !== 'ed25519' || !signed.signature || !signed.manifest) return null;
    if (!signed.manifest.files || typeof signed.manifest.files !== 'object') return null;
    const bytes = canonicalManifestBytes(signed.manifest);
    const ok = edVerify(null, bytes, pubkeyPem, Buffer.from(signed.signature, 'base64'));
    return ok ? signed.manifest : null;
  } catch {
    return null;
  }
}
